FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \    
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        ca-certificates && \  
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



WORKDIR /app

COPY . .

RUN mkdir -p build && cd build && cmake .. && make

CMD ["./build/qfluxion"]